const ADD_MOVIE_FAVORITE = "ADD_MOVIE_FAVORITE";
const GET_MOVIES = "GET_MOVIES";
const REMOVE_MOVIE_FAVORITE = "REMOVE_MOVIE_FAVORITE";
const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";

export {ADD_MOVIE_FAVORITE , GET_MOVIES, REMOVE_MOVIE_FAVORITE, GET_MOVIE_DETAIL}